/* The following code was generated by JFlex 1.4.3 on 16/4/24, 8:21 p. m. */

package codigo;
import static codigo.Tokens.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 16/4/24, 8:21 p. m. from the specification file
 * <tt>C:/Users/aronm/Documents/TEC/Compiladores/Proyectos/1/Proyecto-Compi/App/Analizador/src/codigo/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\6\2\0\1\3\22\0\1\3\1\47\1\7\2\0"+
    "\1\52\1\45\1\10\1\53\1\54\1\12\1\43\1\4\1\44\1\0"+
    "\1\5\1\2\11\2\1\23\1\11\1\51\1\42\1\50\2\0\22\1"+
    "\1\40\7\1\1\57\1\0\1\60\1\0\1\24\1\0\1\26\1\22"+
    "\1\17\1\33\1\32\1\16\1\20\1\37\1\35\2\1\1\15\1\30"+
    "\1\13\1\21\1\25\1\1\1\27\1\41\1\31\1\14\1\1\1\34"+
    "\1\1\1\36\1\1\1\55\1\46\1\56\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\6\2\1\14\1\15\11\2"+
    "\1\16\1\17\1\20\3\21\2\22\1\1\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\4\1\31\1\32\1\33"+
    "\17\2\1\34\3\2\1\35\1\2\1\22\1\36\1\21"+
    "\1\0\1\2\1\37\1\2\1\40\2\2\1\41\14\2"+
    "\1\42\1\2\1\0\1\43\1\44\1\45\1\2\1\46"+
    "\1\47\1\50\1\51\4\2\1\3\1\52\1\53\1\54"+
    "\1\2\1\55";

  private static int [] zzUnpackAction() {
    int [] result = new int[113];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\223\0\304\0\304\0\365\0\61"+
    "\0\61\0\61\0\61\0\u0126\0\u0157\0\u0188\0\u01b9\0\u01ea"+
    "\0\u021b\0\u024c\0\61\0\142\0\u027d\0\u02ae\0\u02df\0\u0310"+
    "\0\u0341\0\u0372\0\u03a3\0\u03d4\0\u0405\0\u0436\0\u0467\0\u0498"+
    "\0\u04c9\0\u04fa\0\u0436\0\u052b\0\u055c\0\u058d\0\u05be\0\61"+
    "\0\61\0\61\0\61\0\61\0\u05ef\0\61\0\61\0\61"+
    "\0\u0620\0\u0651\0\u0682\0\u06b3\0\u06e4\0\u0715\0\u0746\0\u0777"+
    "\0\u07a8\0\u07d9\0\u080a\0\u083b\0\u086c\0\u089d\0\u08ce\0\u08ff"+
    "\0\u0930\0\u0961\0\u0992\0\142\0\u09c3\0\61\0\61\0\61"+
    "\0\u09f4\0\u0a25\0\142\0\u0a56\0\142\0\u0a87\0\u0ab8\0\142"+
    "\0\u0ae9\0\u0b1a\0\u0b4b\0\u0b7c\0\u0bad\0\u0bde\0\u0c0f\0\u0c40"+
    "\0\u0c71\0\u0ca2\0\u0cd3\0\u0d04\0\142\0\u0d35\0\u0d66\0\142"+
    "\0\142\0\142\0\u0d97\0\142\0\142\0\142\0\142\0\u0dc8"+
    "\0\u0df9\0\u0e2a\0\u0e5b\0\61\0\142\0\142\0\142\0\u0e8c"+
    "\0\142";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[113];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\3\1\16\1\17\1\20"+
    "\1\21\1\3\1\22\1\23\1\24\1\25\1\3\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\2\3\1\35"+
    "\1\3\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\52\1\53\1\54"+
    "\62\0\2\3\10\0\10\3\1\0\16\3\21\0\1\4"+
    "\61\0\2\5\61\0\1\55\4\0\1\56\27\0\1\57"+
    "\23\0\1\60\34\0\1\57\17\0\2\3\10\0\1\3"+
    "\1\61\4\3\1\62\1\3\1\0\16\3\20\0\2\3"+
    "\10\0\6\3\1\63\1\3\1\0\16\3\20\0\2\3"+
    "\10\0\1\3\1\64\1\65\3\3\1\66\1\3\1\0"+
    "\2\3\1\67\13\3\20\0\2\3\10\0\10\3\1\0"+
    "\13\3\1\70\2\3\20\0\2\3\10\0\2\3\1\71"+
    "\5\3\1\0\16\3\20\0\2\3\10\0\10\3\1\0"+
    "\12\3\1\72\3\3\20\0\2\3\10\0\10\3\1\0"+
    "\2\3\1\73\13\3\20\0\2\3\10\0\10\3\1\0"+
    "\6\3\1\74\7\3\20\0\2\3\10\0\10\3\1\0"+
    "\2\3\1\75\13\3\20\0\2\3\10\0\10\3\1\0"+
    "\3\3\1\76\12\3\20\0\2\3\10\0\2\3\1\77"+
    "\5\3\1\0\16\3\20\0\2\3\10\0\6\3\1\100"+
    "\1\3\1\0\16\3\20\0\2\3\10\0\10\3\1\0"+
    "\3\3\1\101\7\3\1\102\2\3\20\0\2\3\10\0"+
    "\1\103\2\3\1\104\4\3\1\0\16\3\20\0\2\3"+
    "\10\0\10\3\1\0\5\3\1\105\10\3\61\0\1\106"+
    "\60\0\1\57\1\107\57\0\1\57\1\0\1\107\61\0"+
    "\1\110\61\0\1\110\54\0\1\106\5\0\1\106\52\0"+
    "\1\106\6\0\1\106\51\0\1\57\62\0\1\111\14\0"+
    "\6\55\1\0\52\55\1\0\2\3\10\0\2\3\1\112"+
    "\5\3\1\0\16\3\20\0\2\3\10\0\10\3\1\0"+
    "\5\3\1\113\10\3\20\0\2\3\10\0\1\114\3\3"+
    "\1\115\3\3\1\0\16\3\20\0\2\3\10\0\1\116"+
    "\7\3\1\0\16\3\20\0\2\3\10\0\6\3\1\117"+
    "\1\3\1\0\16\3\20\0\2\3\10\0\10\3\1\0"+
    "\3\3\1\120\12\3\20\0\2\3\10\0\2\3\1\121"+
    "\5\3\1\0\16\3\20\0\2\3\10\0\10\3\1\0"+
    "\2\3\1\122\13\3\20\0\2\3\10\0\6\3\1\123"+
    "\1\3\1\0\16\3\20\0\2\3\10\0\10\3\1\0"+
    "\5\3\1\124\10\3\20\0\2\3\10\0\10\3\1\0"+
    "\3\3\1\125\12\3\20\0\2\3\10\0\10\3\1\0"+
    "\2\3\1\126\13\3\20\0\2\3\10\0\10\3\1\0"+
    "\11\3\1\127\4\3\20\0\2\3\10\0\1\3\1\130"+
    "\6\3\1\0\16\3\20\0\2\3\10\0\10\3\1\0"+
    "\15\3\1\131\20\0\2\3\10\0\1\3\1\132\6\3"+
    "\1\0\16\3\20\0\2\3\10\0\10\3\1\0\11\3"+
    "\1\133\4\3\20\0\2\3\10\0\10\3\1\0\11\3"+
    "\1\134\4\3\20\0\2\3\10\0\10\3\1\0\5\3"+
    "\1\135\10\3\20\0\2\3\10\0\10\3\1\0\3\3"+
    "\1\136\12\3\21\0\1\137\57\0\2\3\10\0\2\3"+
    "\1\140\5\3\1\0\16\3\20\0\2\3\10\0\5\3"+
    "\1\135\2\3\1\0\16\3\20\0\2\3\10\0\4\3"+
    "\1\141\3\3\1\0\16\3\20\0\2\3\10\0\10\3"+
    "\1\0\2\3\1\103\13\3\20\0\2\3\10\0\10\3"+
    "\1\0\15\3\1\130\20\0\2\3\10\0\10\3\1\0"+
    "\3\3\1\135\12\3\20\0\2\3\10\0\7\3\1\142"+
    "\1\0\16\3\20\0\2\3\10\0\10\3\1\0\6\3"+
    "\1\135\7\3\20\0\2\3\10\0\10\3\1\0\2\3"+
    "\1\143\13\3\20\0\2\3\10\0\10\3\1\0\7\3"+
    "\1\144\6\3\20\0\2\3\10\0\1\145\7\3\1\0"+
    "\16\3\20\0\2\3\10\0\10\3\1\0\6\3\1\146"+
    "\7\3\20\0\2\3\10\0\10\3\1\0\6\3\1\147"+
    "\7\3\20\0\2\3\10\0\7\3\1\150\1\0\16\3"+
    "\20\0\2\3\10\0\10\3\1\0\5\3\1\151\10\3"+
    "\20\0\2\3\10\0\2\3\1\152\5\3\1\0\16\3"+
    "\20\0\2\3\10\0\10\3\1\0\11\3\1\153\4\3"+
    "\21\0\1\137\51\0\1\154\5\0\2\3\10\0\10\3"+
    "\1\0\4\3\1\155\11\3\20\0\2\3\10\0\2\3"+
    "\1\124\5\3\1\0\16\3\20\0\2\3\10\0\10\3"+
    "\1\0\6\3\1\156\7\3\20\0\2\3\10\0\10\3"+
    "\1\0\6\3\1\157\7\3\20\0\2\3\10\0\1\160"+
    "\7\3\1\0\16\3\20\0\2\3\10\0\5\3\1\161"+
    "\2\3\1\0\16\3\17\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3773];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\4\11\7\1\1\11\24\1\5\11"+
    "\1\1\3\11\25\1\3\11\1\0\25\1\1\0\14\1"+
    "\1\11\5\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[113];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 134) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 41: 
          { lexeme=yytext(); return Else;
          }
        case 46: break;
        case 35: 
          { return new Symbol(sym.null, yychar, yyline, yytext());
          }
        case 47: break;
        case 42: 
          { return new Symbol(sym.param, yychar, yyline, yytext());
          }
        case 48: break;
        case 7: 
          { return Linea;
          }
        case 49: break;
        case 33: 
          { lexeme=yytext(); return For;
          }
        case 50: break;
        case 22: 
          { lexeme=yytext(); return LLAVECORCHETECIERRA;
          }
        case 51: break;
        case 12: 
          { return new Symbol(sym.sep, yychar, yyline, yytext());
          }
        case 52: break;
        case 31: 
          { return new Symbol(sym.not, yychar, yyline, yytext());
          }
        case 53: break;
        case 20: 
          { lexeme=yytext(); return LLAVEPARENTESISCIERRA;
          }
        case 54: break;
        case 6: 
          { lexeme=yytext(); return Division;
          }
        case 55: break;
        case 18: 
          { lexeme = yytext(); return Op_relacional;
          }
        case 56: break;
        case 17: 
          { lexeme=yytext(); return Op_logico;
          }
        case 57: break;
        case 26: 
          { lexeme = yytext(); return Op_atribucion;
          }
        case 58: break;
        case 30: 
          { lexeme = yytext(); return Op_incremento;
          }
        case 59: break;
        case 24: 
          { lexeme = yytext(); return LLAVECUADRADACIERRA;
          }
        case 60: break;
        case 27: 
          { return new Symbol(sym.cierreComentarioCompuesto, yychar, yyline, yytext());
          }
        case 61: break;
        case 10: 
          { return new Symbol(sym.finalExpresion, yychar, yyline, yytext());
          }
        case 62: break;
        case 8: 
          { lexeme=yytext(); return ComillasD;
          }
        case 63: break;
        case 23: 
          { lexeme = yytext(); return LLAVECUADRADAABRE;
          }
        case 64: break;
        case 45: 
          { lexeme=yytext(); return Cadena;
          }
        case 65: break;
        case 28: 
          { lexeme=yytext(); return Do;
          }
        case 66: break;
        case 13: 
          { return new Symbol(sym.inicioFinDeBloque, yychar, yyline, yytext());
          }
        case 67: break;
        case 9: 
          { lexeme=yytext(); return ComillasS;
          }
        case 68: break;
        case 36: 
          { return new Symbol(sym.func, yychar, yyline, yytext());
          }
        case 69: break;
        case 39: 
          { lexeme=yytext(); return Main;
          }
        case 70: break;
        case 32: 
          { return new Symbol(sym.loc, yychar, yyline, yytext());
          }
        case 71: break;
        case 16: 
          { lexeme=yytext(); return Resta;
          }
        case 72: break;
        case 34: 
          { lexeme=yytext(); return T_dato;
          }
        case 73: break;
        case 14: 
          { lexeme=yytext(); return IGUAL;
          }
        case 74: break;
        case 3: 
          { lexeme=yytext(); return DIGITOS;
          }
        case 75: break;
        case 2: 
          { lexeme=yytext(); return IDENTIFICADOR;
          }
        case 76: break;
        case 38: 
          { return new Symbol(sym.read, yychar, yyline, yytext());
          }
        case 77: break;
        case 37: 
          { return new Symbol(sym.glob, yychar, yyline, yytext());
          }
        case 78: break;
        case 11: 
          { lexeme=yytext(); return Multiplicacion;
          }
        case 79: break;
        case 43: 
          { return new Symbol(sym.write, yychar, yyline, yytext());
          }
        case 80: break;
        case 1: 
          { return ERROR;
          }
        case 81: break;
        case 19: 
          { lexeme=yytext(); return LLAVEPARENTESISABRE;
          }
        case 82: break;
        case 5: 
          { lexeme=yytext(); return COMA;
          }
        case 83: break;
        case 44: 
          { lexeme=yytext(); return While;
          }
        case 84: break;
        case 40: 
          { lexeme = yytext(); return Op_booleano;
          }
        case 85: break;
        case 4: 
          { /*Ignore*/
          }
        case 86: break;
        case 29: 
          { lexeme=yytext(); return If;
          }
        case 87: break;
        case 21: 
          { lexeme=yytext(); return LLAVECORCHETEABRE;
          }
        case 88: break;
        case 25: 
          { return new Symbol(sym.aperturaComentarioCompuesto, yychar, yyline, yytext());
          }
        case 89: break;
        case 15: 
          { lexeme=yytext(); return Suma;
          }
        case 90: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
