
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Apr 17 01:40:20 CST 2024
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIGITOS = 33;
  public static final int Op_relacional = 20;
  public static final int LLAVEPARENTESISCIERRA = 25;
  public static final int Op_booleano = 23;
  public static final int If = 7;
  public static final int T_dato = 4;
  public static final int Else = 8;
  public static final int IDENTIFICADOR = 32;
  public static final int IGUAL = 14;
  public static final int While = 10;
  public static final int Division = 18;
  public static final int Int = 5;
  public static final int Cadena = 6;
  public static final int For = 11;
  public static final int EOF = 0;
  public static final int P_coma = 31;
  public static final int COMILLAS = 3;
  public static final int error = 1;
  public static final int COMA = 35;
  public static final int LLAVEPARENTESISABRE = 24;
  public static final int Linea = 2;
  public static final int LLAVECUADRADACIERRA = 29;
  public static final int Op_atribucion = 21;
  public static final int Do = 9;
  public static final int ERROR = 34;
  public static final int Op_logico = 19;
  public static final int COMILLAD = 12;
  public static final int FUNC = 13;
  public static final int LLAVECORCHETEABRE = 26;
  public static final int Resta = 16;
  public static final int Multiplicacion = 17;
  public static final int LLAVECUADRADAABRE = 28;
  public static final int Op_incremento = 22;
  public static final int Suma = 15;
  public static final int Main = 30;
  public static final int LLAVECORCHETECIERRA = 27;
}

