
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Apr 16 20:21:51 CST 2024
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIGITOS = 34;
  public static final int Op_relacional = 21;
  public static final int ComillasD = 12;
  public static final int LLAVEPARENTESISCIERRA = 26;
  public static final int Op_booleano = 24;
  public static final int If = 7;
  public static final int T_dato = 4;
  public static final int Else = 8;
  public static final int IDENTIFICADOR = 33;
  public static final int IGUAL = 15;
  public static final int While = 10;
  public static final int Division = 19;
  public static final int Int = 5;
  public static final int Cadena = 6;
  public static final int For = 11;
  public static final int EOF = 0;
  public static final int P_coma = 32;
  public static final int error = 1;
  public static final int COMA = 36;
  public static final int LLAVEPARENTESISABRE = 25;
  public static final int Linea = 2;
  public static final int LLAVECUADRADACIERRA = 30;
  public static final int Op_atribucion = 22;
  public static final int ERROR = 35;
  public static final int Do = 9;
  public static final int Op_logico = 20;
  public static final int FUNC = 14;
  public static final int LLAVECORCHETEABRE = 27;
  public static final int Resta = 17;
  public static final int ComillasS = 13;
  public static final int Multiplicacion = 18;
  public static final int LLAVECUADRADAABRE = 29;
  public static final int Op_incremento = 23;
  public static final int Suma = 16;
  public static final int Main = 31;
  public static final int Comillas = 3;
  public static final int LLAVECORCHETECIERRA = 28;
}

